검색화면 메인화면
mash-up-kr/HikingClub_iOS pull request #50
Opened 2021-11-02 08:39 UTC by namsoo5

## 이슈번호
#43 
## 작업내용 
- 검색텍스트필드
- 최근검색어 리스트
- 카테고리 리스트
## 스크린샷
<img width="223" alt="image" src="https://user-images.githubusercontent.com/35462671/139812254-84db6382-1abb-442e-ba64-f30b8fc73183.png">

2021-11-02 14:56 UTC, dvHuni requested changes

2021-11-02 14:56 UTC, dvHuni commented on HikingClub/Feature/Search/Cell/RecentSearchCollectionViewCell.swift
> +    private(set) var disposeBag: DisposeBag = DisposeBag()
이건 어떤 의미일까용가리

2021-11-02 14:56 UTC, dvHuni commented on HikingClub/Feature/Search/Cell/RecentSearchCollectionViewCell.swift
> +    @IBOutlet fileprivate weak var deleteButton: UIButton!
fileprivate을 선택한 이유는 먼가용가리

2021-11-02 14:56 UTC, dvHuni commented on HikingClub/Feature/Search/SearchViewController.swift
> +//        layout.estimatedItemSize = UICollectionViewFlowLayout.automaticSize
주석 남긴 이유가 있을까 ?

2021-11-02 14:56 UTC, dvHuni commented on HikingClub/Feature/Search/SearchViewController.swift
> +
viewDidLoad가 내용이 없다면 override 하지 않아도 될듯 !

2021-11-02 14:56 UTC, dvHuni commented on HikingClub/Feature/Search/SearchViewController.swift
> +        viewModel.recentSearchWords
bind, subscribe 같은 내용은 bind 함수 안에서 작성하려 했는데 혹시 컨벤션 맞춰줄수 있나 ?

2021-11-02 14:56 UTC, dvHuni commented on HikingClub/Feature/Search/SearchViewController.swift
> +        viewModel.categoryWords
⬆️ 위와 같은 내용

2021-11-02 14:56 UTC, dvHuni commented on HikingClub/Feature/Search/SearchViewModel.swift
> +import RxSwift
RxSwift 없어도 될듯!

2021-11-03 06:36 UTC, namsoo5 commented on HikingClub/Feature/Search/Cell/RecentSearchCollectionViewCell.swift
> +    private(set) var disposeBag: DisposeBag = DisposeBag()
셀 밖에서써야하는데
수정하면 안돼기때문에
set권한만 private함

2021-11-03 06:37 UTC, namsoo5 commented on HikingClub/Feature/Search/Cell/RecentSearchCollectionViewCell.swift
> +    @IBOutlet fileprivate weak var deleteButton: UIButton!
rx익스텐션으로 사용하기위해서 private는 불가하기하다오

2021-11-03 06:37 UTC, namsoo5 commented on HikingClub/Feature/Search/SearchViewController.swift
> +//        layout.estimatedItemSize = UICollectionViewFlowLayout.automaticSize
아 삭제못함 까먹어따능
처리하겟다능

2021-11-03 06:38 UTC, namsoo5 commented on HikingClub/Feature/Search/SearchViewController.swift
> +
있다없어져서 못지웟네 삭제처리하겟다능

2021-11-03 06:38 UTC, namsoo5 commented on HikingClub/Feature/Search/SearchViewController.swift
> +        viewModel.recentSearchWords
컬랙션뷰 만드는 로직이긴해서 컬랙션뷰로 따로뺏는데
모든 rx는 바인드로가는건가??

2021-11-03 06:40 UTC, namsoo5 commented on HikingClub/Feature/Search/SearchViewModel.swift
> +import RxSwift
쓸일이 생길거긴한데 우선지워놓겟삼 ㅎㅎ

2021-11-03 06:46 UTC, dvHuni commented on HikingClub/Feature/Search/SearchViewController.swift
> +//        layout.estimatedItemSize = UICollectionViewFlowLayout.automaticSize
삭제 커밋 올리면 Reslove 하겠음!

2021-11-03 06:53 UTC, dvHuni commented on HikingClub/Feature/Search/SearchViewController.swift
> +
삭제 커밋 올리면 Reslove 하갔어

2021-11-03 06:54 UTC, dvHuni commented on HikingClub/Feature/Search/SearchViewController.swift
> +        viewModel.recentSearchWords
bind, subscribe는 바인드에서 처리하려고 생각했음

특히 viewModel의 relay를 bind, subscribe 하는거!

2021-11-06 09:26 UTC, dvHuni approved these changes

2021-11-06 14:54 UTC, merged