Mj/home table view
mash-up-kr/HikingClub_iOS pull request #53
Opened 2021-11-04 10:51 UTC by 32moon

## 이슈번호
#18 

## 작업내용 
RoadTableView, RoadTableViewCell UI작업

## 스크린샷
<img width="341" alt="스크린샷 2021-11-04 오후 7 50 31" src="https://user-images.githubusercontent.com/73117833/140301339-b4f6baf5-243d-4282-862f-4d78e99ac136.png">

2021-11-04 11:41 UTC, dvHuni requested changes
ChangePassword 2.swift 등 xxx 2 파일이 생긴것 같은데 ..

이거 지워야될듯?

2021-11-04 11:41 UTC, dvHuni commented on HikingClub/Feature/Home/HomeViewModel.swift
> +import RxRelay
굳굳~!! 👍

2021-11-04 11:41 UTC, dvHuni commented on HikingClub/Feature/Home/HomeViewController.swift
> +import RxSwift
RxSwift 모듈은 없어도 될것같은데 ?

2021-11-04 11:41 UTC, dvHuni commented on HikingClub/Feature/Home/View/Road/TableViewCell/RoadTableViewCell.swift
> +        roadTitleLabel.setFont(.semiBold16)
이렇게 주석으로 구분하는것 보다 함수를 나누는게 더 보기 편해~!!

2021-11-04 12:26 UTC, namsoo5 reviewed
첫PR 고생해쒀~~

2021-11-04 12:26 UTC, namsoo5 commented on HikingClub/Feature/Home/HomeViewController.swift
> +import RxSwift
disposebag쓰려고 내가 세트로 써~ 한거라서
지우면댈듯 ㅎㅎ

2021-11-04 12:26 UTC, namsoo5 commented on HikingClub/Feature/Home/View/Road/TableViewCell/RoadTableViewCell.swift
> +        roadTitleLabel.setFont(.semiBold16)
하나하나안쓰고
우리가 봐도 이해하기 어려울거같다? 알아야할거같은거에 달면좋음!~😎

2021-11-06 07:40 UTC, dvHuni approved these changes

2021-11-06 07:45 UTC, merged